name: Use AWS CDK
description: Steps to use AWS CDK

inputs:
  role:
    description: AWS role ARN to assume
    type: string
    required: true

runs:
  using: "composite"

  steps:
    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: ap-southeast-2

    - name: Install AWS CDK
      shell: bash
      run: |
        cd cdk && npm install
